version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - app-network

  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mariadb:latest
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8181:80"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
